### PR TITLE
pie chart supports RGBAColor

### PR DESCRIPTION
**Pull request by wangjiawen2013**
Make pie chart support RGBAColor, which is very usefull when overlaying multi-layers plots.

### CODE REVIEW

**Comment by wangjiawen2013** [comment]
This will solve the issue: https://github.com/plotters-rs/plotters/issues/597

**Comment by AaronErhardt** [comment]
Since this is a breaking change, I cannot merge this into master but only `next-relase-devel`. Can you change the target branch?

**Comment by wangjiawen2013** [comment]
Ok, I will change the target branch. By the way, what is "breaking change" ? Will you merge changes which are not "breaking change" in master (such as `evcxr_figure_with_saving`) to "next-release-devel" ？If not, There will be more and more difference between master and next-release-devel and the features/enhancements in master will not appear in next-release-devel.

**Comment by wangjiawen2013** [comment]
Ok, I will change the target branch. By the way, what is "breaking change" ? Will you merge changes which are not "breaking change" in master (such as `evcxr_figure_with_saving`) to "next-release-devel" ？If not, There will be more and more difference between master and next-release-devel and the features/enhancements in master will not appear in next-release-devel.

**Comment by AaronErhardt** [comment]
> By the way, what is "breaking change"?

https://doc.rust-lang.org/cargo/reference/semver.html

**Pull request closed without merging**
