### PR TITLE
Pie Element

### PR DESCRIPTION
**Pull request by hhamana**
Implements a high-level element to conveniently draw pie charts (#207 )

This is probably just a first draft implementation, as many parts might benefit from deeper abstraction.
As this works mostly with polar coordinates however, I am not sure which traits would make sense to implement.

Some parts that might be interesting to split off for re-usability, maybe:
- polar coordinates (as ranged2d, along with Cartesian?)
- radians (ranged 1d? std already offers `to_radians()` on f64, not sure what would be the benefit of a newtype).

There are a few flaws, which don't look like plotters offers any better way around:
- This currently draws the arc by calculating a finite number of points, and drawing straight lines in-between. 
Best would be to draw a bezier line that would let me just define the start, middle and end point for each wedge, but I haven't found a way to do so. Due to this, the pie might look aliased at times.
- The backend wants i32 for finite pixels, but the pie works with f64 for radians. Conversion between the two types is lossy. This might create bumps due to coordinates rounding, which doesn't help the first point with aliasing. DrawingBackend should accept floating points coordinates and figure out how to draw smooth half-pixels.

### CODE REVIEW

**Comment by AaronErhardt** [comment]
I'd be happy if you want to submit this here: https://github.com/plot-rs/plotters

For reference: https://github.com/38/plotters/issues/341

**Comment by AaronErhardt** [comment]
Now that plotters is back, I think you have to revert all those changed links :wink:

**Comment by 38** [comment]
Hi, thanks for contribute. This is awesome! Just have a look at the PR, it looks good to me. 

A few comment: 

> * polar coordinates (as ranged2d, along with Cartesian?)

Yes, that is what I was planning to do - but I think this approach is good for now. 

> This currently draws the arc by calculating a finite number of points, and drawing straight lines in-between.
Best would be to draw a bezier line that would let me just define the start, middle and end point for each wedge, but I haven't found a way to do so. Due to this, the pie might look aliased at times.

Yes, this is limited by the backend interface - this requires a change to the backend crate. I think it would be easy to add but I think it's good for now.

> The backend wants i32 for finite pixels, but the pie works with f64 for radians. Conversion between the two types is lossy. This might create bumps due to coordinates rounding, which doesn't help the first point with aliasing. DrawingBackend should accept floating points coordinates and figure out how to draw smooth half-pixels.

Also this has been discussed before - also a backend API limit that we may want to improve in the future. 

Please let me know if you have any questions.

Cheers!

**Comment by 38** [comment]
Merged the PR, thanks!

**Pull request merged**
