### PR TITLE
Add dashed line style.

### PR DESCRIPTION
**Pull request by KmolYuan**
A simple work similar to `LineSeries` and `PathElement`.

# New Types

Added `DashedLineSeries` (under `line_series` feature) and `DashedPathElement`.

+ `plotters::series::line_series::DashedLineSeries` - A simple type just making `std::iter::once(element)` by implementing `IntoIterator`, and has the same options as the element type.
+ `plotters::element::basic_shapes::DashedPathElement` - A element type drawing dashed lines pixel-wised.

# Options

+ `points`: The iterator of the points.
+ `size`: The dash size.
+ `spacing`: The dash-to-dash spacing (gap size).
+ `style`: The shape style.

# ⚠️ Known Issue

+ ~If the points are too dense, it will become a solid line.~ (solved)
+ Distortion in rounding coordinates, mainly in SVG.

# Preview

Use blue line. The cross markers are the input points.

```rust
let series = DashedLineSeries::new(points, 10, 5, color);
chart.draw_series(series)?.label(label).legend(move |(x, y)| {
    DashedPathElement::new([(x, y), (x + 20, y)], 10, 5, color)
});
```

Another SVG example of my work is 3D coordinates. The curves are projected on a sphere, the main shape using a red dashed line, and the mechanism behind the sphere is shown with gray dashed lines.

### CODE REVIEW

**Comment by KmolYuan** [comment]
This is a solution for anyone who wants to use dashed lines.
References: #321 #295 #324

**Review by AaronErhardt — APPROVED** [review]
Looks good to me. Is it ready to merge?

**Comment by KmolYuan** [comment]
@AaronErhardt Sure, thanks for your review!

**Comment by gitmalong** [comment]
Does this also allow `configure_series_labels` to use a dashed border?

**Comment by KmolYuan** [comment]
@gitmalong 
> Does this also allow `configure_series_labels` to use a dashed border?

Currently not. It needs a custom drawing function setting for the border style.

**Pull request merged**
